# Path to your oh-my-zsh installation.
export ZSH="/Users/felipefaria/.oh-my-zsh"

# Theme
ZSH_THEME="prose"

# Plugins
plugins=(git pyenv)

# Path to coreutils.
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# Sourcing oh-my-zsh.
source $ZSH/oh-my-zsh.sh
